package com.example.logindemo.dto;

/**
 * @author hrh13
 * @date 2021/8/11
 */
public class PermissionConstantValue {
    public static final String USER_FIND = "USER_FIND", USER_UPDATE = "USER_UPDATE", USER_DELETE = "USER_DELETE",
            EMPLOYEE_ROLE_ADD = "EMPLOYEE_ROLE_ADD", EMPLOYEE_ROLE_FIND = "EMPLOYEE_ROLE_FIND",
            EMPLOYEE_ROLE_UPDATE = "EMPLOYEE_ROLE_UPDATE", EMPLOYEE_ROLE_DELETE = "EMPLOYEE_ROLE_DELETE",
            ROLE_ADD = "ROLE_ADD", ROLE_UPDATE = "ROLE_UPDATE", ROLE_DELETE = "ROLE_DELETE",
            ROLE_PERMISSION_FIND = "ROLE_PERMISSION_FIND", ROLE_PERMISSION_DELETE = "ROLE_PERMISSION_DELETE",
            ROLE_PERMISSION_ADD = "ROLE_PERMISSION_ADD", ROLE_PERMISSION_UPDATE = "ROLE_PERMISSION_UPDATE";
}
