spring.jpa.hibernate.ddl-auto: update

spring.datasource.url: jdbc:mysql://192.168.56.1:3306/login
spring.datasource.username: root
spring.datasource.password: root
#spring.datasource.driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true
spring:
  jpa:
    open-in-view: false
  redis:
    port: 6379
    host: 192.168.1.117
  rabbitmq:
    port: 5672
    host: 192.168.1.117
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        log-in-0:
          group=hello:
logging:
  file:
    name: F:/loginDemoLog/login.log
  level:
    com:
      example:
        logindemo:
          service: debug
